version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: TIENDA
    volumes:
      - ./mariadb_data:/var/lib/mysql:rw
      - ./Muebles.sql:/docker-entrypoint-initdb.d/init.sql:ro
    user: mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
    ports:
      - 9093:80
    depends_on:
      - mariadb
    networks:
      - backend

  python:
    build: .
    container_name: python
    environment:
      PYTHONUNBUFFERED: 1
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_DATABASE: TIENDA
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
    ports:
      - 9094:8080
    depends_on:
      - mariadb
    networks:
      - backend
  
  apache:
    build: ./apache
    container_name: apache
    ports:
      - 7777:80
    volumes:
      - ./apache/static:/var/www/html
    networks:
      - backend

networks:
  backend:
    driver: bridge